require("beautiful").init(require("gears").filesystem.get_configuration_dir() .. "themes/linear/theme.lua")
require("themes.linear.bar")
require("themes.linear.title")
require("themes.linear.volume")
require("themes.linear.brightness")
require("themes.linear.launcher")
require("themes.linear.power")
require("themes.linear.systray")
require("themes.linear.notif")
