#!/bin/bash

nitrogen --restore &
picom &
$HOME/.config/bin/bar.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nm-applet &
xsettingsd & 

# xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VGA-1 --off --output DP-1 --off --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2 --off --output HDMI-2 --off &
