runtime! defaults.vim

" Fix st
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
if &term =~ '^st\($\|-\)'
  set ttymouse=sgr
endif

color theme
syntax on

nnoremap y "+y
vnoremap y "+y
nnoremap p "+p
vnoremap p "+p

set titlestring=VIM\ %F\ %a%r%m titlelen=70

set tabstop=4
set shiftwidth=4
