#!/bin/sh

run() {
	if ! pgrep -f "$1" ; then
		"$@"&
	fi
}

run /usr/bin/prime-offload
run picom
run xsettingsd
run nm-applet
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
run xrdb merge .Xresources
