#!/bin/sh

run() {
  if ! pgrep -f "$1" ;
  then
    "$@"&
  fi
}

run picom
run xsettingsd
run nm-applet
run cbatticon
run volumeicon
run light-locker --no-lock-on-lid
run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
